# Generated by Django 5.2.10 on 2026-01-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logo/')),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('emp_prefix', models.CharField(default='EMP', max_length=10)),
            ],
        ),
    ]
