# Generated by Django 4.2.26 on 2026-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.AddField(
            model_name='holiday',
            name='calendar_file',
            field=models.FileField(blank=True, null=True, upload_to='holiday_calendars/'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
