# Generated by Django 4.2.26 on 2026-01-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_alter_holiday_options_holiday_calendar_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Holiday Calendar', max_length=100)),
                ('file', models.FileField(upload_to='holiday_calendar/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='calendar_file',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='created_at',
        ),
    ]
