# Generated by Django 4.2.26 on 2026-01-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_holidaycalendar_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaycalendar',
            name='title',
        ),
        migrations.AlterField(
            model_name='holidaycalendar',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
