# Generated by Django 5.2.10 on 2026-01-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
