# Generated by Django 5.2.10 on 2026-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leave_rejection_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_half_day',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('FIRST_HALF', '1st Half'), ('SECOND_HALF', '2nd Half')], default='FULL', max_length=15),
        ),
    ]
