# Generated by Django 5.2.10 on 2026-01-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AddField(
            model_name='leave',
            name='is_comp_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_half_day',
            field=models.CharField(choices=[('FULL', 'Full Day'), ('HALF', 'Half Day')], default='FULL', max_length=10),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_days',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leaves_taken',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='leaves.leavetype'),
        ),
    ]
