# Generated by Django 5.2.10 on 2026-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leave_options_alter_leave_is_half_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={},
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leaves_taken',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='total_leaves',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='paid_leave',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
