# Generated by Django 5.2.10 on 2026-03-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leavebalance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='casual_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='paid_leave',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='sick_leave',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
