# Generated by Django 5.2.10 on 2026-01-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={},
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_days',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
