# Generated by Django 4.2.26 on 2026-01-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
