# Generated by Django 5.2.10 on 2026-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='relieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='relieved_file',
            field=models.FileField(blank=True, null=True, upload_to='employees/relieving_docs/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='relieved_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
