# Generated by Django 5.2.10 on 2026-02-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_relieved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='employees.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
