# Generated by Django 4.2.26 on 2026-01-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='pancard_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
