# Generated by Django 5.2.10 on 2026-01-27 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employeeprofile_aadhaar_number_and_more'),
        ('organization', '0002_organization_created_at_organization_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.organization'),
        ),
    ]
