# Generated by Django 5.2.10 on 2026-01-27 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeprofile_address_employeeprofile_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Indian phone number', regex='^(\\+91)?[6-9]\\d{9}$')]),
        ),
    ]
