# Generated by Django 5.2.10 on 2026-01-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeeprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
