# Generated by Django 5.2.10 on 2026-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='relationship',
        ),
        migrations.AddField(
            model_name='familymember',
            name='daughter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='son_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
