# Generated by Django 5.2.10 on 2026-01-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_familymember_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
