# Generated by Django 5.2.10 on 2026-02-11 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypolicy',
            old_name='effective_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companypolicy',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance')], max_length=20),
        ),
    ]
